---
- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd config
  shell: "containerd config default | tee /etc/containerd/config.toml"
  args:
    executable: /bin/bash

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: true
    
- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Create .kube directory for devops user
  file:
    path: /home/devops/.kube
    state: directory
    owner: devops
    group: devops
    mode: 0700

- name: Copy admin kubeconfig for devops user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/devops/.kube/config
    owner: devops
    group: devops
    mode: 0644
    remote_src: yes

- name: Install Kube Flannel network plugin as devops user
  become: yes
  become_user: devops
  shell: |
    kubectl apply -f kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  args:
    executable: /bin/bash
