---
- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd config
  shell: "containerd config default | tee /etc/containerd/config.toml"
  args:
    executable: /bin/bash

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: true
    
- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Create .kube directory for devops user
  file:
    path: /home/devops/.kube
    state: directory
    owner: devops
    group: devops
    mode: 0700

- name: Copy admin kubeconfig for devops user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/devops/.kube/config
    owner: devops
    group: devops
    mode: 0644
    remote_src: yes


- name: Create .kube directory for jenkins user
  file:
    path: /var/lib/jenkins/.kube
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: Copy admin kubeconfig for jenkins user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /var/lib/jenkins/.kube/config
    owner: jenkins
    group: jenkins
    mode: 0644
    remote_src: yes

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Ensure kernel modules load at boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: "br_netfilter\n"

- name: Set Kubernetes sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables=1
      net.bridge.bridge-nf-call-ip6tables=1
      net.ipv4.ip_forward=1

- name: Apply sysctl params
  command: sysctl --system

- name: Install Kube Flannel network plugin as devops user
  become: yes
  become_user: root
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  args:
    executable: /bin/bash

- name: Remove all taints from a node
  become: yes
  shell: |
    NODE=$(hostname)
    echo "Detected Kubernetes node name: $NODE"
    taints=$(kubectl get node $NODE -o jsonpath='{.spec.taints[*].key}' --kubeconfig /etc/kubernetes/admin.conf)

    if [ -n "$taints" ]; then
      for t in $taints; do
        echo "Removing taint $t from node $NODE"
        kubectl taint nodes $NODE "$t"- --kubeconfig /etc/kubernetes/admin.conf
      done
    else
      echo "No taints found on node $NODE"
    fi
  args:
    executable: /bin/bash

- name: Check if ingress-nginx already installed if not then install it
  become: yes
  shell: |
    kubectl get ns ingress-nginx >/dev/null 2>&1 --kubeconfig /etc/kubernetes/admin.conf || \
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml --kubeconfig /etc/kubernetes/admin.conf
  args:
    executable: /bin/bash
