apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-helm.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-helm.name" . }}
      annotations:
        helm.sh/release-time: "{{ now | quote }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
            #env:
            #- name: NODE_ENV
            #  value: {{ .Values.env.NODE_ENV | quote }}
            #- name: PORT
            #  value: {{ .Values.env.PORT | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "app-helm.fullname" . }}-config
          ports:
            - containerPort: {{ .Values.service.targetPort }}
